[package]
name = "merle-view"
description = "Minimal image viewer binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true
authors.workspace = true

[dependencies]
merle-raw.workspace = true
merle-loader.workspace = true

[lints]
workspace = true
