[package]
name = "merle-view"
description = "Fast-start image viewer binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true
authors.workspace = true

[dependencies]
merle-photo.workspace = true
merle-loader.workspace = true
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
pollster.workspace = true
bytemuck.workspace = true

[lints]
workspace = true
